import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "../context/AuthContext";
import { UsersAPI } from "../api/client";
import { Button } from "../components/ui/Button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "../components/ui/Card";
import { Dialog } from "../components/ui/Dialog";
import toast from "react-hot-toast";
import {
  Users,
  UserPlus,
  Shield,
  User,
  MoreVertical,
  Edit,
  Trash2,
  X,
  Check,
  AlertTriangle,
  Key,
} from "lucide-react";
import { useRef, useEffect } from "react";

export default function UsersPage() {
  const { isAdmin, user } = useAuth();
  const queryClient = useQueryClient();
  const [showInviteDialog, setShowInviteDialog] = useState(false);
  const [inviteRole, setInviteRole] = useState("cashier");
  const [createdAccount, setCreatedAccount] = useState(null); // Store created account details
  const [editingUser, setEditingUser] = useState(null);
  const [deleteConfirm, setDeleteConfirm] = useState(null);
  const [viewingCredentials, setViewingCredentials] = useState(null); // User whose credentials are being viewed
  const [credentials, setCredentials] = useState(null);
  const [loadingCredentials, setLoadingCredentials] = useState(false);

  const usersQuery = useQuery({
    queryKey: ["users"],
    queryFn: () => UsersAPI.list(),
    enabled: isAdmin,
  });

  const inviteMutation = useMutation({
    mutationFn: (data) => UsersAPI.invite(data),
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["users"] });
      
      // Always show password (it's always returned now)
      setCreatedAccount({
        username: data.login_username || data.email,
        password: data.password,
        name: data.name,
      });
      toast.success("User created successfully! Share the login details.");
    },
    onError: (e) => {
      toast.error(e?.response?.data?.detail || "Failed to create user");
    },
  });

  const updateRoleMutation = useMutation({
    mutationFn: ({ userId, role }) => UsersAPI.updateRole(userId, role),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["users"] });
      queryClient.invalidateQueries({ queryKey: ["profile"] });
      toast.success("User role updated");
      setEditingUser(null);
    },
    onError: (e) => {
      toast.error(e?.response?.data?.detail || "Failed to update role");
    },
  });

  const removeMutation = useMutation({
    mutationFn: (userId) => UsersAPI.remove(userId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["users"] });
      toast.success("User removed");
      setDeleteConfirm(null);
    },
    onError: (e) => {
      toast.error(e?.response?.data?.detail || "Failed to remove user");
    },
  });

  const handleInvite = (e) => {
    e.preventDefault();
    // Username and password are auto-generated by backend
    inviteMutation.mutate({ role: inviteRole });
  };

  const handleRoleChange = (userId, newRole) => {
    updateRoleMutation.mutate({ userId, role: newRole });
  };

  const handleRemove = (userId) => {
    removeMutation.mutate(userId);
  };

  const handleViewCredentials = async (user) => {
    setViewingCredentials(user);
    setLoadingCredentials(true);
    setCredentials(null);
    try {
      const creds = await UsersAPI.getCredentials(user.id);
      setCredentials(creds);
    } catch (e) {
      // Don't show toast for "password not stored" - show it in the dialog instead
      const errorMsg = e?.response?.data?.detail || "Failed to load credentials";
      if (errorMsg.includes("Password not stored")) {
        // Keep dialog open to show the helpful message
        setCredentials(null);
      } else {
        toast.error(errorMsg);
        setViewingCredentials(null);
      }
    } finally {
      setLoadingCredentials(false);
    }
  };

  if (!isAdmin) {
    return (
      <div className="flex items-center justify-center min-h-[50vh]">
        <Card className="max-w-md">
          <CardContent className="py-12 text-center">
            <Shield className="w-12 h-12 mx-auto mb-4 text-slate-400" />
            <h3 className="text-lg font-semibold text-slate-700 dark:text-slate-200 mb-2">
              Access Restricted
            </h3>
            <p className="text-slate-500 dark:text-slate-400">
              Only administrators can manage users.
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  const users = usersQuery.data || [];
  const currentUser = user?.id;

  return (
    <div className="space-y-4 sm:space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 sm:gap-4">
        <div>
          <h1 className="text-xl sm:text-2xl font-bold text-slate-800 dark:text-white">
            Team Members
          </h1>
          <p className="text-slate-500 dark:text-slate-400 mt-1">
            Manage users and their roles
          </p>
        </div>
        <Button
          size="sm"
          onClick={() => setShowInviteDialog(true)}
        >
          <UserPlus size={18} />
          Invite User
        </Button>
      </div>

      {usersQuery.isLoading ? (
        <Card>
          <CardContent className="py-12 text-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
          </CardContent>
        </Card>
      ) : usersQuery.isError ? (
        <Card>
          <CardContent className="py-12 text-center">
            <AlertTriangle className="w-12 h-12 mx-auto mb-4 text-red-500" />
            <p className="text-red-600 dark:text-red-400">
              Failed to load users. Please try again.
            </p>
          </CardContent>
        </Card>
      ) : users.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <Users className="w-12 h-12 mx-auto mb-4 text-slate-400" />
            <h3 className="text-lg font-semibold text-slate-700 dark:text-slate-200 mb-2">
              No team members yet
            </h3>
            <p className="text-slate-500 dark:text-slate-400 mb-4">
              Invite users to join your store
            </p>
            <Button onClick={() => setShowInviteDialog(true)}>
              <UserPlus size={18} />
              Invite First User
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4">
          {users.map((user) => (
            <Card key={user.id}>
              <CardContent className="py-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4 flex-1 min-w-0">
                    <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-blue-600 rounded-full flex items-center justify-center text-white font-semibold text-lg flex-shrink-0">
                      {user.email?.charAt(0).toUpperCase() || "U"}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <p className="font-semibold text-slate-800 dark:text-white truncate">
                          {user.name || user.email}
                        </p>
                        {user.id === currentUser && (
                          <span className="text-xs px-2 py-0.5 rounded-full bg-blue-100 dark:bg-blue-900/50 text-blue-700 dark:text-blue-300">
                            You
                          </span>
                        )}
                      </div>
                      <p className="text-sm text-slate-500 dark:text-slate-400 truncate">
                        {user.email}
                      </p>
                      <div className="flex items-center gap-2 mt-1">
                        {user.role === "admin" ? (
                          <span className="inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full bg-purple-100 dark:bg-purple-900/50 text-purple-700 dark:text-purple-300">
                            <Shield size={12} />
                            Admin
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300">
                            <User size={12} />
                            Cashier
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                  {user.id !== currentUser && (
                    <div className="flex items-center gap-2">
                      <UserActionsMenu
                        user={user}
                        onRoleChange={handleRoleChange}
                        onRemove={() => setDeleteConfirm(user)}
                        onViewCredentials={handleViewCredentials}
                      />
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Invite Dialog */}
      <Dialog
        open={showInviteDialog && !createdAccount}
        onClose={() => {
          setShowInviteDialog(false);
          setInviteRole("cashier");
        }}
        title="Create New User"
      >
        <form onSubmit={handleInvite} className="space-y-4">
          <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-3 mb-4">
            <p className="text-sm text-blue-800 dark:text-blue-200">
              <User size={16} className="inline mr-2" />
              Username and password will be auto-generated and shown to you.
            </p>
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              Role
            </label>
            <select
              value={inviteRole}
              onChange={(e) => setInviteRole(e.target.value)}
              className="w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-700 px-4 py-2 text-slate-800 dark:text-white focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 outline-none"
            >
              <option value="cashier">Cashier</option>
              <option value="admin">Admin</option>
            </select>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Username will be auto-generated (e.g., "cashier1", "cashier2", etc.)
            </p>
          </div>
          <div className="flex gap-2 pt-2">
            <Button
              type="button"
              variant="secondary"
              onClick={() => {
                setShowInviteDialog(false);
                setInviteRole("cashier");
              }}
              className="flex-1"
            >
              Cancel
            </Button>
            <Button type="submit" disabled={inviteMutation.isPending} className="flex-1">
              {inviteMutation.isPending ? "Creating..." : "Create User"}
            </Button>
          </div>
        </form>
      </Dialog>

      {/* Account Created Dialog - Show password */}
      <Dialog
        open={!!createdAccount}
        onClose={() => {
          setCreatedAccount(null);
          setShowInviteDialog(false);
          setInviteRole("cashier");
        }}
        title="User Created Successfully"
      >
        <div className="space-y-4">
          <p className="text-slate-600 dark:text-slate-400">
            Share these login details with <strong>{createdAccount?.name}</strong>:
          </p>
          <div className="bg-slate-50 dark:bg-slate-800 rounded-lg p-4 space-y-3">
            <div>
              <label className="text-xs text-slate-500 dark:text-slate-400 mb-1 block">
                Username/Email
              </label>
              <div className="flex items-center gap-2">
                <code className="flex-1 bg-white dark:bg-slate-700 px-3 py-2 rounded border border-slate-200 dark:border-slate-600 text-sm font-mono">
                  {createdAccount?.username}
                </code>
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={() => {
                    navigator.clipboard.writeText(createdAccount?.username || "");
                    toast.success("Copied!");
                  }}
                >
                  Copy
                </Button>
              </div>
            </div>
            <div>
              <label className="text-xs text-slate-500 dark:text-slate-400 mb-1 block">
                Password
              </label>
              <div className="flex items-center gap-2">
                <code className="flex-1 bg-white dark:bg-slate-700 px-3 py-2 rounded border border-slate-200 dark:border-slate-600 text-sm font-mono">
                  {createdAccount?.password}
                </code>
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={() => {
                    navigator.clipboard.writeText(createdAccount?.password || "");
                    toast.success("Copied!");
                  }}
                >
                  Copy
                </Button>
              </div>
            </div>
          </div>
          <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-3">
            <p className="text-sm text-blue-800 dark:text-blue-200">
              <Key size={16} className="inline mr-2" />
              You can view these credentials anytime by clicking the "..." menu next to the user and selecting "View Credentials".
            </p>
          </div>
          <Button
            onClick={() => {
              setCreatedAccount(null);
              setShowInviteDialog(false);
              setInviteRole("cashier");
            }}
            className="w-full"
          >
            Done
          </Button>
        </div>
      </Dialog>

      {/* Delete Confirmation */}
      {deleteConfirm && (
        <Dialog
          open={!!deleteConfirm}
          onClose={() => setDeleteConfirm(null)}
          title="Remove User"
        >
          <div className="space-y-4">
            <p className="text-slate-600 dark:text-slate-400">
              Are you sure you want to remove{" "}
              <span className="font-semibold">{deleteConfirm.email}</span> from
              your store? They will no longer have access.
            </p>
            <div className="flex gap-2 pt-2">
              <Button
                variant="secondary"
                onClick={() => setDeleteConfirm(null)}
                className="flex-1"
              >
                Cancel
              </Button>
              <Button
                variant="danger"
                onClick={() => handleRemove(deleteConfirm.id)}
                disabled={removeMutation.isPending}
                className="flex-1"
              >
                {removeMutation.isPending ? "Removing..." : "Remove User"}
              </Button>
            </div>
          </div>
        </Dialog>
      )}

      {/* View Credentials Dialog */}
      <Dialog
        open={!!viewingCredentials}
        onClose={() => {
          setViewingCredentials(null);
          setCredentials(null);
        }}
        title="User Credentials"
      >
        {loadingCredentials ? (
          <div className="py-12 text-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
            <p className="text-slate-500 dark:text-slate-400 mt-4">Loading credentials...</p>
          </div>
        ) : credentials ? (
          <div className="space-y-4">
            <p className="text-slate-600 dark:text-slate-400">
              Login credentials for <strong>{credentials.name || credentials.email}</strong>:
            </p>
            <div className="bg-slate-50 dark:bg-slate-800 rounded-lg p-4 space-y-3">
              <div>
                <label className="text-xs text-slate-500 dark:text-slate-400 mb-1 block">
                  Username/Email
                </label>
                <div className="flex items-center gap-2">
                  <code className="flex-1 bg-white dark:bg-slate-700 px-3 py-2 rounded border border-slate-200 dark:border-slate-600 text-sm font-mono">
                    {credentials.login_username}
                  </code>
                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={() => {
                      navigator.clipboard.writeText(credentials.login_username);
                      toast.success("Copied!");
                    }}
                  >
                    Copy
                  </Button>
                </div>
              </div>
              <div>
                <label className="text-xs text-slate-500 dark:text-slate-400 mb-1 block">
                  Password
                </label>
                <div className="flex items-center gap-2">
                  <code className="flex-1 bg-white dark:bg-slate-700 px-3 py-2 rounded border border-slate-200 dark:border-slate-600 text-sm font-mono">
                    {credentials.password}
                  </code>
                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={() => {
                      navigator.clipboard.writeText(credentials.password);
                      toast.success("Copied!");
                    }}
                  >
                    Copy
                  </Button>
                </div>
              </div>
            </div>
            <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg p-3">
              <p className="text-sm text-amber-800 dark:text-amber-200">
                <AlertTriangle size={16} className="inline mr-2" />
                Keep these credentials secure. Share them only with the user.
              </p>
            </div>
            <Button
              onClick={() => {
                setViewingCredentials(null);
                setCredentials(null);
              }}
              className="w-full"
            >
              Close
            </Button>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="py-8 text-center">
              <AlertTriangle className="w-12 h-12 mx-auto mb-4 text-amber-500" />
              <h3 className="text-lg font-semibold text-slate-700 dark:text-slate-200 mb-2">
                Password Not Available
              </h3>
              <p className="text-slate-600 dark:text-slate-400 mb-4">
                The password for this user is not stored in the system. This may happen if:
              </p>
              <ul className="text-sm text-slate-500 dark:text-slate-400 text-left max-w-md mx-auto space-y-1 mb-4">
                <li>• The user was created before password storage was enabled</li>
                <li>• The user has changed their password</li>
                <li>• The user was created with email (not auto-generated)</li>
              </ul>
              <p className="text-sm text-slate-500 dark:text-slate-400">
                You can ask the user to use the "Forgot Password" feature to reset their password.
              </p>
            </div>
            <Button
              onClick={() => {
                setViewingCredentials(null);
                setCredentials(null);
              }}
              className="w-full"
            >
              Close
            </Button>
          </div>
        )}
      </Dialog>
    </div>
  );
}

function UserActionsMenu({ user, onRoleChange, onRemove, onViewCredentials }) {
  const [open, setOpen] = useState(false);
  const menuRef = useRef(null);

  useEffect(() => {
    const handleClickOutside = (e) => {
      if (menuRef.current && !menuRef.current.contains(e.target)) {
        setOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  return (
    <div className="relative" ref={menuRef}>
      <button
        onClick={() => setOpen(!open)}
        className="p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors"
      >
        <MoreVertical size={18} className="text-slate-600 dark:text-slate-400" />
      </button>
      {open && (
        <div className="absolute right-0 top-full mt-2 w-48 bg-white dark:bg-slate-800 rounded-xl shadow-xl border border-slate-200 dark:border-slate-700 py-2 z-50">
          <button
            onClick={() => {
              onViewCredentials(user);
              setOpen(false);
            }}
            className="w-full flex items-center gap-3 px-4 py-2 text-sm text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors"
          >
            <Key size={16} />
            View Credentials
          </button>
          <button
            onClick={() => {
              const newRole = user.role === "admin" ? "cashier" : "admin";
              onRoleChange(user.id, newRole);
              setOpen(false);
            }}
            className="w-full flex items-center gap-3 px-4 py-2 text-sm text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors"
          >
            <Edit size={16} />
            Change to {user.role === "admin" ? "Cashier" : "Admin"}
          </button>
          <button
            onClick={() => {
              onRemove();
              setOpen(false);
            }}
            className="w-full flex items-center gap-3 px-4 py-2 text-sm text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
          >
            <Trash2 size={16} />
            Remove User
          </button>
        </div>
      )}
    </div>
  );
}

